//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.RLTrainnerPkg
{
    [Serializable]
    public class Float32IDMsgMsg : Message
    {
        public const string k_RosMessageName = "RL_trainner_pkg/Float32IDMsg";
        public override string RosMessageName => k_RosMessageName;

        // Float32IDMsg.msg
        public int id;
        public float[] data;

        public Float32IDMsgMsg()
        {
            this.id = 0;
            this.data = new float[0];
        }

        public Float32IDMsgMsg(int id, float[] data)
        {
            this.id = id;
            this.data = data;
        }

        public static Float32IDMsgMsg Deserialize(MessageDeserializer deserializer) => new Float32IDMsgMsg(deserializer);

        private Float32IDMsgMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.id);
            deserializer.Read(out this.data, sizeof(float), deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.id);
            serializer.WriteLength(this.data);
            serializer.Write(this.data);
        }

        public override string ToString()
        {
            return "Float32IDMsgMsg: " +
            "\nid: " + id.ToString() +
            "\ndata: " + System.String.Join(", ", data.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
