//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.RLTrainnerPkg
{
    [Serializable]
    public class TransitionMsgMsg : Message
    {
        public const string k_RosMessageName = "RL_trainner_pkg/TransitionMsg";
        public override string RosMessageName => k_RosMessageName;

        //  TransitionMsg.msg
        public Std.MultiArrayLayoutMsg layout;
        public float[] state;
        public float[] action;
        public float[] reward;
        public bool trancated_flag;
        public float[] next_state;

        public TransitionMsgMsg()
        {
            this.layout = new Std.MultiArrayLayoutMsg();
            this.state = new float[0];
            this.action = new float[0];
            this.reward = new float[0];
            this.trancated_flag = false;
            this.next_state = new float[0];
        }

        public TransitionMsgMsg(Std.MultiArrayLayoutMsg layout, float[] state, float[] action, float[] reward, bool trancated_flag, float[] next_state)
        {
            this.layout = layout;
            this.state = state;
            this.action = action;
            this.reward = reward;
            this.trancated_flag = trancated_flag;
            this.next_state = next_state;
        }

        public static TransitionMsgMsg Deserialize(MessageDeserializer deserializer) => new TransitionMsgMsg(deserializer);

        private TransitionMsgMsg(MessageDeserializer deserializer)
        {
            this.layout = Std.MultiArrayLayoutMsg.Deserialize(deserializer);
            deserializer.Read(out this.state, sizeof(float), deserializer.ReadLength());
            deserializer.Read(out this.action, sizeof(float), deserializer.ReadLength());
            deserializer.Read(out this.reward, sizeof(float), deserializer.ReadLength());
            deserializer.Read(out this.trancated_flag);
            deserializer.Read(out this.next_state, sizeof(float), deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.layout);
            serializer.WriteLength(this.state);
            serializer.Write(this.state);
            serializer.WriteLength(this.action);
            serializer.Write(this.action);
            serializer.WriteLength(this.reward);
            serializer.Write(this.reward);
            serializer.Write(this.trancated_flag);
            serializer.WriteLength(this.next_state);
            serializer.Write(this.next_state);
        }

        public override string ToString()
        {
            return "TransitionMsgMsg: " +
            "\nlayout: " + layout.ToString() +
            "\nstate: " + System.String.Join(", ", state.ToList()) +
            "\naction: " + System.String.Join(", ", action.ToList()) +
            "\nreward: " + System.String.Join(", ", reward.ToList()) +
            "\ntrancated_flag: " + trancated_flag.ToString() +
            "\nnext_state: " + System.String.Join(", ", next_state.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
