//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.RLTrainnerPkg
{
    [Serializable]
    public class ProcessArrayResponse : Message
    {
        public const string k_RosMessageName = "RL_trainner_pkg/ProcessArray";
        public override string RosMessageName => k_RosMessageName;

        public Std.Float32MultiArrayMsg output;

        public ProcessArrayResponse()
        {
            this.output = new Std.Float32MultiArrayMsg();
        }

        public ProcessArrayResponse(Std.Float32MultiArrayMsg output)
        {
            this.output = output;
        }

        public static ProcessArrayResponse Deserialize(MessageDeserializer deserializer) => new ProcessArrayResponse(deserializer);

        private ProcessArrayResponse(MessageDeserializer deserializer)
        {
            this.output = Std.Float32MultiArrayMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.output);
        }

        public override string ToString()
        {
            return "ProcessArrayResponse: " +
            "\noutput: " + output.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
