//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.RLTrainnerPkg
{
    [Serializable]
    public class ProcessArrayRequest : Message
    {
        public const string k_RosMessageName = "RL_trainner_pkg/ProcessArray";
        public override string RosMessageName => k_RosMessageName;

        //  ProcessArray.srv
        public Std.Float32MultiArrayMsg input;

        public ProcessArrayRequest()
        {
            this.input = new Std.Float32MultiArrayMsg();
        }

        public ProcessArrayRequest(Std.Float32MultiArrayMsg input)
        {
            this.input = input;
        }

        public static ProcessArrayRequest Deserialize(MessageDeserializer deserializer) => new ProcessArrayRequest(deserializer);

        private ProcessArrayRequest(MessageDeserializer deserializer)
        {
            this.input = Std.Float32MultiArrayMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.input);
        }

        public override string ToString()
        {
            return "ProcessArrayRequest: " +
            "\ninput: " + input.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
